version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smartphone-catalog-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
