version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: smartphone-catalog-prod
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
